# Site settings
title: Shree Ji Corporation
email: your-email@domain.com
description: "Shree Ji Corporation, Textile and Yarn Merchants since 1980, Established in Textile Hub, Bhilwara."
url: http://shreeji.co
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ShreeJiCo
  - title: facebook
    url:
  - title: google-plus
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: Office 6, Khabya Market, Bada Bazar
  - line: Bhilwara, Rajastan 311001, India

# Build settings
markdown: kramdown
permalink: pretty
